<table cellpadding="0" cellspacing="0" class="top">
	<tr>
		<td>			
			<!--a href="http://spasiboyandex.ru/"><img src="images/design/ya_logo.gif" alt=""/></a><br/>
			<a href="http://spasiboyandex.ru/" class="textlink">Клиенты найдутся</a><br/-->
			<a href="http://telestroka.ru/"><img src="images/design/logo.gif" alt="" class="logo" style="margin-top: 60px;"/></a>
			<a href="http://telestroka.ru/" class="textlink">
				<h1><span class="blue">tele</span>STROKA.ru</h1>
				ТВ. Бегущая строка <br/>
				Введите текст — узнайте стоимость!
			</a>
		</td>
	</tr>
</table>